### ISSUE TITLE
running gui apps in lxd

### ISSUE THREAD

**Issue by bmullan** [AlexandreDey/ContainerBox#6]
Not sure if you have seen Simos Xenitellis'd blog on LXD related technology but he recently updated an original post of his about "_running graphics accelerated gui apps in lxd_".   In the following Blog post (see URL below) Simos demostrates using a newly created GUI "profile" to use when launching an LXD container you can share the HOST's graphics & sound devices.    (see his lxdguiprofile.txt file for how/what is done https://blog.simos.info/wp-content/uploads/2018/06/lxdguiprofile.txt)

https://blog.simos.info/how-to-easily-run-graphics-accelerated-gui-apps-in-lxd-containers-on-your-ubuntu-desktop/

I thought this might help you with ContainerBox.

Brian

**Comment by AlexandreDey** [comment]
Hi,

When I started working on ContainerBox, creating a profile was a possibility. But I realised it wasn't the solution because it is statically defined so you always passthrough the same display socket (in that case the main one), so if you want to create multiple GUI containers, you either create multiple profiles (which essentially defeats the goal of profiles...), or they share the same display which leads to bad behaviours (funny things can happen if you start multiple DE on the same display) but more importantly high security risks (X11 is a bad protocol when it comes to security: as long as you have access to the display socket, you can listen to any input and capture the screen of every other client).

In ContainerBox, I used a more versatile approach that creates a new display server when you start the container and dedicate this display server to this container only (so that if the container is corrupted, it cannot eavesdrop what others do with the display).

Same goes for pulseaudio
